In [3]:
import pandas as pd
import warnings 

warnings.filterwarnings('ignore')

fake=pd.read_csv('Fake.csv')
true=pd.read_csv('True.csv')

In [4]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
print(fake.shape)
print(true.shape)

(23481, 4)
(21417, 4)

In [8]:
fake['label']='FAKE'
true['label']="TRUE"

df=pd.concat([fake,true])

In [9]:
df=df.sample(
    frac=1,random_state=42,
).reset_index(drop=True)

In [10]:
print(df["label"].value_counts())

label
FAKE    23481
TRUE    21417
Name: count, dtype: int64

In [11]:
df.columns

Index(['title', 'text', 'subject', 'date', 'label'], dtype='str')

In [13]:
print(df.shape)
print(df['label'].value_counts())

(44898, 5)
label
FAKE    23481
TRUE    21417
Name: count, dtype: int64

In [14]:
df=df.drop('date',axis=1)
df.columns

Index(['title', 'text', 'subject', 'label'], dtype='str')

In [15]:
df["content"] = (
    df["title"] +
    " " +
    df["text"]
)

In [17]:
X=df['content']
y=df['label']

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer()

X=vectorizer.fit_transform(X)

In [21]:
X.shape

(44898, 122513)

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,random_state=42,test_size=0.2
)

In [23]:
from sklearn.naive_bayes import  MultinomialNB

model=MultinomialNB()

model.fit(X_train,y_train)

MultinomialNB()

In [24]:
y_pred=model.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.9527839643652561
[[4479  231]
 [ 193 4077]]
              precision    recall  f1-score   support

        FAKE       0.96      0.95      0.95      4710
        TRUE       0.95      0.95      0.95      4270

    accuracy                           0.95      8980
   macro avg       0.95      0.95      0.95      8980
weighted avg       0.95      0.95      0.95      8980

In [27]:
news = input("Enter news article: ")

news_vector = vectorizer.transform([news])

prediction = model.predict(news_vector)

print("Prediction:", prediction[0])

Prediction: FAKE